export const texts = {
  artworks: {
    "polyphonic-embodiments": {
      title: "Polyphonic Embodiment(s)",
      author: "Amina Abbas-Nazari",
      bio: "Amina Abbas-Nazari is a practicing designer, researcher, and vocal performer who has researched the voice in conjunction with emerging technology since 2008. She completed a Techne funded PhD in the School of Communication at the Royal College of Art, investigating the sound and sounding of voices in artificially intelligent machine listening and conversational systems, having previously studied RCA MA Design Interactions. Their work has been presented internationally including the London Design Festival, Design Museum, Barbican Centre, V&A, Lisson Gallery London, Milan Furniture Fair, Venice Architecture Biennial, Critical Media Lab, Switzerland, Litost Gallery, Prague, Pedreira, Portugal and Harvard University, America. She has performed internationally with choirs and regularly collaborates with artists as an experimental vocalist.",
      description: "Polyphonic Embodiment(s) (2019-2022) aims to reveal and resist how AI transcribes understandings of voice onto notions of identity. The project involved recreating a voice-to-face recognition AI that claims to be able to tell what your face looks like from the sound of your voice. The video documentation for this project shows ‘facial’ images produced by the voice-to-face recognition AI, when activated by my voice, modified with simple DIY devices. The speculative nature of the project is not to suggest that people should modify their voices in interaction with AI communication systems. Rather the simple devices work with bodily architecture as a mailable sonic instrument to explore vocal potential and exaggerate my voice as a material. As the project title suggests, the work invites people to consider the multidimensional nature of voice and vocal identity from an embodied standpoint. It calls for contemplation of the relationships between voice and identity, and individuals having multiple or evolving versions of identity. The collaboration with the recreated AI software creates a feedback loop to reflect on how peoples’ vocal sounding is ‘seen’ by AI, to contest the way voices are currently heard, comprehended and utilised by AI and the AI industry. In turn this sheds light on the normative assumptions contained within AI’s readings of voice and its relationships to facial image and identity construction.<br><br>Polyphonic Embodiment(s) is a project produced in collaboration with Nestor Pestana with AI development by Sitraka Rakotoniaina."
    },
    "dandelions": {
      title: "Dandelions",
      author: "David Young",
      bio: "David Young is an artist exploring how emerging technologies shape and limit human perception. Working with AI and quantum computing, he creates meditative images that reveal hidden assumptions embedded in technological innovation. Drawing on decades of experience with advanced computation, Young treats code and algorithms as materials for reflection rather than spectacle. His work challenges technological monoculture, inviting viewers to imagine more humane, democratic futures for technology where aesthetic experience takes center stage. Young's work is held in collections including Kunstmuseum Bonn and has been featured in Artforum. He holds degrees from MIT's Media Lab and UC Santa Cruz, and lives in New York.",
      description: "Dandelions (2020) represent a profound meditation on transformation and impermanence through artificial intelligence. Created by training machine learning algorithms on photographs Young captured of dandelions at their most fleeting moment — the brief transition from yellow flower to white seed head — the work exists in a liminal space between photography and abstraction.<br><br>Using an intentionally small dataset of just a couple dozen images rather than millions, Young employs what he calls 'Little AI' as opposed to Big Tech approaches. By constraining the technology, the machine struggles to create something accurate, sometimes breaking down to produce unrecognisable outputs. The resulting artworks hover between realistic interpretations and machine-generated geometric patterns, creating luminous combinations that transcend traditional representation.<br><br>Sometimes the machine renders patterns that existed in the original image data but were invisible to human perception, revealing the limitations of our own observation. The dandelion, in its transition from flower to seed, becomes a totemic image of impermanence and the point of tension right before everything explodes and the seeds of change are disseminated. The artist suggests these works serve as a metaphor for our current moment — 'a fragile world blowing apart, but ready with the seeds for a new future'."
    },
    "curse-of-dimensionality": {
      title: "Curse of Dimensionality",
      author: "Philipp Schmitt",
      bio: "Philipp Schmitt (he/him) is an artist and designer based in Hamburg, Germany. For the last decade, his creative practice has engaged with the philosophical, poetic, and political dimensions of computation. His works include installations, artist books, websites, photography, lecture performance, and sound. Philipp’s work has been exhibited at The Photographers' Gallery London, Philadelphia Museum of Art, MAK Vienna, Science Gallery Dublin, and Triennale Milano. Works are in the collections of the Philadelphia Museum of Art and Ars Electronica Center. He is the recipient of a NYFA Artist Fellowship (2023) and a Berggruen Fellowship (2019–21).",
      description: "In Curse of Dimensionality (2020), the title phrase names a difficulty in mathematics: how spaces with many dimensions, central to machine learning models, become counterintuitive for human understanding and impossible to visualise. AI researchers frequently insist on the objectivity and rationality of their methods and, often, their character. Yet working in this space, of which all images can only be partial projections, requires of the scientist an intuition for the unimaginable.<br><br>The work generates collages of diagrams and phrases taken from AI research papers that mention high-dimensional spaces. Here the diagrams, meant as clarifications, instead expose the limits of representation and the imaginative, subjective work required to navigate the unimaginable.<br><br>Archived. Available <a href='https://curseofdimensionality.science/' style='color: #678486;'>here</a>. Live: November 1st, 2o25 — March 31st, 2o26."
    },
    "kaoyao": {
      title: "KaoYao",
      author: "Luisa Grigorian",
      bio: "Luisa Grigorian is a multimedia artist, who is interested in observing contexts, symbols, signs, and conveying new ways of communication and perception through interactive experiences using the web (mostly p5js). Graduated from HSE Art&Design school (2021–2025). Participated in some exhibitions: The Art of the Book. School, Publishing House, Community, HSE ART GALLERY (2025); Demodulation 2024, Yandex Museum (2024); Through the Looking Glass and Back, Arkhangelskoe (2024); Telling Stories. Big Data, MMOMA (2023).",
      description: "KaoYao (2025) is an interactive experience exploring emotions, their perception, and recognition. Using machine facial recognition, the web-art project reads users’ expressions and offers the mood in the form of generative kaomoji (｀·∀·´). Computer vision reads facial expressions in real time, determining the range of emotional states (positive, negative, active, passive). Based on this analysis, the site's algorithm generates complex kaomoji, which are divided by etymological or morphological features.<br><br>Common simplified understanding suggests that there are six dominant human emotions (anger, fear, surprise, disgust, happiness, and sadness) while in many languages there are broader and more complex concepts. Drawing on unique descriptions of emotions in different languages, the Mistral language model suggests names and descriptions for kaomoji, so users can have a look at their emotions from a different angle and without trying to recognize them, but get an evaluative inference compiled on the basis of neural vision and unique linguistic combinations."
    },
    "mercedes-clr-gtr": {
      title: "Mercedes CLR GTR",
      author: "Lev Pereulkov & Tanya Bronnikova",
      bio: "tanya bronnikova — kazan-based artist, smena gallery resident, blueprint 100 finalist (2023). lev pereulkov — independent artist.",
      description: "no problem! here's the information about the mercedes CLR GTR: <br>the mercedes CLR GTR is a remarkable racing car, it delivers over 600 horsepower. acceleration from 0 to 100 km/h takes approximately 3.7 seconds, with a remarkable top speed surprising 320 km/h. what's particularly fascinating is how this acceleration compounds over time — each increment of speed requires exponentially more power, yet the system demands constant acceleration regardless of the driver's intent. the standard unit for acceleration is meters per second squared (m/s^2) (2025). "
    },
    "reconstructions": {
      title: "Reconstructions",
      author: "Allison Parrish",
      bio: "Allison Parrish is a computer programmer, poet, and game designer whose teaching and practice address the unusual phenomena that blossom when language and computers meet. She is an Associate Arts Professor at NYU’s Interactive Telecommunications Program.",
      description: "Reconstructions (2020) is an infinite computer-generated poem whose output conforms to the literary figure of chiasmus. The program samples a sequence of text from a variational autoencoder neural network trained on millions of lines of English poetry, and pairs that line with a reconstruction of the sequence in reverse order. The lines of poetry thereby produced are semantic and syntactic mirror images of one another, exhibiting a classic chiastic X structure: ABBA. At regular intervals, the system produces a new pair of lines, which are then displayed between the lines of the previous step, creating a chiastic structure in the arrangement not just of words within lines but among the lines themselves. As the program progresses, lines continue to appear in the middle of each pair, leading to an endlessly nested chiastic structure (ABCCBA, ABCDDCBA, ABCDEEDCBA, etc.). Older lines fade as they move away from the center but are never fully erased from the screen."
    },
    "autonomy-of-a-fall": {
      title: "Autonomy of a Fall",
      author: "Soyun Park, Olympia Kotopoulos & Bregje Benecke",
      bio: "Soyun Park is a South Korean interdisciplinary artist, researcher, and educator based in The Hague, Netherlands. Her work studies the relationship between the political structures of media technology and the human body. She gazes at these subjects through critical and humorous perspectives, choreographing audiovisual devices that challenge the boundaries of cinema. Investigating the power dynamics of surveillance and machine learning software embedded in society and bodies, she employs resistance, trespassing, and hacking in the act of making, using them as tools to reveal underlying predicaments.<br><br>Olympia Kotopoulos, originally from Sydney, Australia, is an independent movement artist who has worked internationally as a performer and maker for over a decade. Driven by an interest in virtuosic communication through the body, she freelances across Europe as a dancer, maker, rehearsal director, and dramaturg. Her artistic practice explores the relationship between movement and new media, guided by research and alternative storytelling. Investigating the archival nature of motion, she examines human patterning and development within performative contexts, seeking connection, innovation, and transformation through embodied experience.<br><br>Bregje Benecke is an audiovisual artist exploring how perception, classification, and context shape our understanding of reality. Fascinated by the subjective processes behind meaning-making, she examines how systems of knowledge and observation define what is seen, valued, or excluded. Through these systems, we do not merely order reality; we shape it — and are shaped by it. Her past work and research draw on phenomena such as phantom pain, human echolocation, and outdated scientific knowledge to reveal the fragile mechanics through which we experience, question, and construct the world we think we know.",
      description: "An ongoing research.<br><br>This research was initiated through Moving Media Lab (November 2023–March 2025), supported by Cinedans. We thank Moving Media Lab for providing a platform where research between bodies and technology can thrive.<br><br>In this theatrical experiment, 3 artists explore the tension between subjective experience and external classification through the act of falling. Using surveillance, machine learning, and collective decision-making, it exposes the power dynamics at play when bodies are categorized, interpreted, and controlled.<br><br>Our bodies act as both site and source of inward reflection and of external interpretation. This research seeks to extend beyond individual experiences to all kinds of bodies in varied environments, questioning how personal histories, embodied memory, and external gaze intersect in processes of classification.<br><br>Project produced in collaboration with Stijn Balk, Machine Learning advisor (2025)."
    },
    "trajectories": {
      title: "Trajectories",
      author: "Adelina Fishova",
      bio: "Adelina Fishova is a multidisciplinary artist and designer holding a BA in Design from HSE University, Moscow. Her practice focuses on the intersection of computational technologies, visual arts and poetic writing. She is particularly interested in the ephemeral qualities of digital processes and how reframing them beyond utilitarian roles enables a sensorial and poetic experience. She has participated in exhibitions at HSE Art Gallery, Winzavod Center for Contemporary Art, GROUND Solyanka, Moscow Museum of Modern Art.",
      description: "— Where do birds fly when the sky runs out?<br>— What do fish stay silent about when their eyes meet?<br>— How much time does a snail carry on its back?<br><br>Trajectories (2025) is a video series that uses a computer vision model to recognize animals and track their movements. Birds, insects, invisible streams of air — their paths become a form of writing. Words emerge at the intersection of natural rhythms and computational processes, forming ephemeral poetic structures.<br><br>Each fragment begins with a metaphorical open-ended question addressed to the neural network. Moving beyond the utilitarian prompt, these questions disrupt the algorithm’s logic and transform the dialogue with the machine into a space for poetic exploration."
    },
    "focus": {
      title: "Focus",
      author: "Adelina Fishova",
      bio: "Adelina Fishova is a multidisciplinary artist and designer holding a BA in Design from HSE University, Moscow. Her practice focuses on the intersection of computational technologies, visual arts and poetic writing. She is particularly interested in the ephemeral qualities of digital processes and how reframing them beyond utilitarian roles enables a sensorial and poetic experience. She has participated in exhibitions at HSE Art Gallery, Winzavod Center for Contemporary Art, GROUND Solyanka, Moscow Museum of Modern Art.",
      description: "— How long can you hold a word at your fingertips?<br><br>Focus (2025) is an interactive experience exploring the nature of attention. By bringing the thumb and forefinger together, the viewer creates a point of focus where scattered letters begin to gather into words, forming real-time generated poems. This simple physical gesture becomes a metaphor for concentration, turning noise into meaning, randomness into poetry. It gives the drifting digital gaze a tangible form, recalling the creative and transformative power of attention. Yet the meaning it creates is fragile: as soon as focus drifts, the text dissolves again.<br><br>The experience begins with a metaphorical open-ended question addressed to the neural network. Moving beyond the utilitarian prompt, this question transforms the dialogue with the machine into a space for poetic exploration."
    },
    "select-important-things": {
      title: "select important things",
      author: "Jane Frances Dunlop",
      bio: "Jane Frances Dunlop is an artist, writer and educator. She creates installations, videos, essays, poems and performances. Dunlop has exhibited and performed in galleries and cultural institutions internationally including Kunstlerhaus (Vienna), Turner Contemporary (Margate, UK) and ACMI (Melbourne). Her writing has appeared in academic journals, art catalogues and magazines. Dunlop holds a PhD and is a Senior Lecturer in Digital Media at the University of Greenwich in London, UK.",
      description: "The voice is a marker of personhood, a deliverer of information, a piece of biometric data. In select important things (voices), knowledge system videos – short videos combining stock footage with anecdote and autotheortical reflections – are arranged as a chorus, straining a single voice’s ability to make sense. What is at stake as voices come together - in crowds of political protest, in the choruses of historical and contemporary performance and in the composites generated by “machine intelligences”?<br><br>select important things (voices, 2022–ongoing) is part of crowds choruses composites, a series of explorations, artworks and critical reflections that focus on the literal and metaphorical ways a voice is constructed and construed in this context. The project brings together a body of artworks that interrogate knowledge making in the 21st century, responding to the cultural and social shifts brought on by two crises of knowledge that have come to define the last decade: the rise of ‘alternative facts’ that undermine and destabilise expertise, and the increasingly complex AI systems for which datasets operate as intelligence. Thinking technology through performance, the project investigates collective intelligence in an era of mass information. The result is a series of explorations into public masses, aestheticized publics, and the dataset that mechanise, capture and conflate those mass human intelligences."
    },
    "for-ruth-and-violette": {
      title: "For Ruth & Violette",
      author: "Paul O’Neill",
      bio: "Paul O'Neill is an artist and assistant professor at the Huston School of Film & Digital Media, University of Galway, Ireland. His research and practice are concerned with our collective dependency on networked technologies and infrastructures. His research has featured in publications from the Institute of Network Cultures (Amsterdam) and ANNEX – Ireland’s representative at the 2021 Venice Architecture Biennale, and he has exhibited and presented his work at galleries and institutions including Science Gallery (Ireland), Ars Electronica (Austria), NeMe (Cyprus), Onassis Stegi (Greece) and SAW (Canada).",
      description: "For Ruth & Violette (2021) utilises poetry and encryption to subvert networked communications infrastructures. Based on a code-poem used by intelligence operatives in the Second World War, the piece harnesses alternative uses of the video conferencing platform Zoom to engage with the complex history of obfuscation in relation to covert broadcasting methods. The title of the project is in reference to the origins of the poem and the lives encoded within it."
    }
  }
};
